In [68]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [69]:
df = pd.read_csv(r"D:\Study\Testing dataset\CSV data\StudentPerformanceFactors.csv")

In [70]:
df.head()

,Hours_Studied,Attendance,Parental_Involvement,Access_to_Resources,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,Tutoring_Sessions,Family_Income,Teacher_Quality,School_Type,Peer_Influence,Physical_Activity,Learning_Disabilities,Parental_Education_Level,Distance_from_Home,Gender,Exam_Score
0,23,84,Low,High,No,7,73,Low,Yes,0,Low,Medium,Public,Positive,3,No,High School,Near,Male,67
1,19,64,Low,Medium,No,8,59,Low,Yes,2,Medium,Medium,Public,Negative,4,No,College,Moderate,Female,61
2,24,98,Medium,Medium,Yes,7,91,Medium,Yes,2,Medium,Medium,Public,Neutral,4,No,Postgraduate,Near,Male,74
3,29,89,Low,Medium,Yes,8,98,Medium,Yes,1,Medium,Medium,Public,Negative,4,No,High School,Moderate,Male,71
4,19,92,Medium,Medium,Yes,6,65,Medium,Yes,3,Medium,High,Public,Neutral,4,No,College,Near,Female,70

In [71]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6607 entries, 0 to 6606
Data columns (total 20 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Hours_Studied               6607 non-null   int64
 1   Attendance                  6607 non-null   int64
 2   Parental_Involvement        6607 non-null   object
 3   Access_to_Resources         6607 non-null   object
 4   Extracurricular_Activities  6607 non-null   object
 5   Sleep_Hours                 6607 non-null   int64
 6   Previous_Scores             6607 non-null   int64
 7   Motivation_Level            6607 non-null   object
 8   Internet_Access             6607 non-null   object
 9   Tutoring_Sessions           6607 non-null   int64
 10  Family_Income               6607 non-null   object
 11  Teacher_Quality             6529 non-null   object
 12  School_Type                 6607 non-null   object
 13  Peer_Influence              6607 non-null   object
 14  Physical_Activity           6607 non-null   int64
 15  Learning_Disabilities       6607 non-null   object
 16  Parental_Education_Level    6517 non-null   object
 17  Distance_from_Home          6540 non-null   object
 18  Gender                      6607 non-null   object
 19  Exam_Score                  6607 non-null   int64
dtypes: int64(7), object(13)
memory usage: 1.0+ MB

In [72]:
df.shape

(6607, 20)

In [73]:
df.describe()

,Hours_Studied,Attendance,Sleep_Hours,Previous_Scores,Tutoring_Sessions,Physical_Activity,Exam_Score
count,6607.000000,6607.000000,6607.00000,6607.000000,6607.000000,6607.000000,6607.000000
mean,19.975329,79.977448,7.02906,75.070531,1.493719,2.967610,67.235659
std,5.990594,11.547475,1.46812,14.399784,1.230570,1.031231,3.890456
min,1.000000,60.000000,4.00000,50.000000,0.000000,0.000000,55.000000
25%,16.000000,70.000000,6.00000,63.000000,1.000000,2.000000,65.000000
50%,20.000000,80.000000,7.00000,75.000000,1.000000,3.000000,67.000000
75%,24.000000,90.000000,8.00000,88.000000,2.000000,4.000000,69.000000
max,44.000000,100.000000,10.00000,100.000000,8.000000,6.000000,101.000000

In [74]:
df = df.dropna()

In [75]:
df.tail()

,Hours_Studied,Attendance,Parental_Involvement,Access_to_Resources,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,Tutoring_Sessions,Family_Income,Teacher_Quality,School_Type,Peer_Influence,Physical_Activity,Learning_Disabilities,Parental_Education_Level,Distance_from_Home,Gender,Exam_Score
6602,25,69,High,Medium,No,7,76,Medium,Yes,1,High,Medium,Public,Positive,2,No,High School,Near,Female,68
6603,23,76,High,Medium,No,8,81,Medium,Yes,3,Low,High,Public,Positive,2,No,High School,Near,Female,69
6604,20,90,Medium,Low,Yes,6,65,Low,Yes,3,Low,Medium,Public,Negative,2,No,Postgraduate,Near,Female,68
6605,10,86,High,High,Yes,6,91,High,Yes,2,Low,Medium,Private,Positive,3,No,High School,Far,Female,68
6606,15,67,Medium,Low,Yes,9,94,Medium,Yes,0,Medium,Medium,Public,Positive,4,No,Postgraduate,Near,Male,64

In [76]:
from sklearn.preprocessing import LabelEncoder, StandardScaler, MinMaxScaler
from sklearn.model_selection import train_test_split, RandomizedSearchCV
from sklearn.pipeline import Pipeline

In [77]:
from sklearn.neural_network import MLPRegressor
from sklearn.linear_model import ElasticNet
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import AdaBoostRegressor, BaggingRegressor, RandomForestRegressor, StackingRegressor

In [78]:
from sklearn.ensemble import GradientBoostingRegressor

In [79]:
df.columns

Index(['Hours_Studied', 'Attendance', 'Parental_Involvement',
       'Access_to_Resources', 'Extracurricular_Activities', 'Sleep_Hours',
       'Previous_Scores', 'Motivation_Level', 'Internet_Access',
       'Tutoring_Sessions', 'Family_Income', 'Teacher_Quality', 'School_Type',
       'Peer_Influence', 'Physical_Activity', 'Learning_Disabilities',
       'Parental_Education_Level', 'Distance_from_Home', 'Gender',
       'Exam_Score'],
      dtype='object')

In [80]:
encoder = LabelEncoder()
for features in ['Parental_Involvement', 'Access_to_Resources', 'Extracurricular_Activities', 'Motivation_Level', 'Internet_Access', 'Family_Income', 'School_Type', 'Peer_Influence', 'Teacher_Quality','Learning_Disabilities', 'Parental_Education_Level', 'Distance_from_Home','Gender']:
    df[features] = encoder.fit_transform(df[features])

In [81]:
df.head(10)

,Hours_Studied,Attendance,Parental_Involvement,Access_to_Resources,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,Tutoring_Sessions,Family_Income,Teacher_Quality,School_Type,Peer_Influence,Physical_Activity,Learning_Disabilities,Parental_Education_Level,Distance_from_Home,Gender,Exam_Score
0,23,84,1,0,0,7,73,1,1,0,1,2,1,2,3,0,1,2,1,67
1,19,64,1,2,0,8,59,1,1,2,2,2,1,0,4,0,0,1,0,61
2,24,98,2,2,1,7,91,2,1,2,2,2,1,1,4,0,2,2,1,74
3,29,89,1,2,1,8,98,2,1,1,2,2,1,0,4,0,1,1,1,71
4,19,92,2,2,1,6,65,2,1,3,2,0,1,1,4,0,0,2,0,70
5,19,88,2,2,1,8,89,2,1,3,2,2,1,2,3,0,2,2,1,71
6,29,84,2,1,1,7,68,1,1,1,1,2,0,1,2,0,1,1,1,67
7,25,78,1,0,1,6,50,2,1,1,0,0,1,0,2,0,1,0,1,66
8,17,94,2,0,0,6,80,0,1,0,2,1,0,1,1,0,0,2,1,69
9,23,98,2,2,1,8,71,2,1,0,0,0,1,2,5,0,1,1,1,72

In [82]:
Y = df.iloc[:, -1]
X = df.iloc[:, 0:-1]

In [83]:
x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, train_size=0.8, random_state= 42, shuffle= True)

In [84]:
base_model = [('KNN', KNeighborsRegressor()), ('Net', ElasticNet())]

In [85]:
stack = StackingRegressor(estimators= base_model, final_estimator= GradientBoostingRegressor())

In [86]:
pipe = Pipeline([('Scaler', MinMaxScaler()), ('model', stack)])

In [87]:
param = {
        'model__KNN__n_neighbors': [5, 10, 15, 20], 
        'model__KNN__weights':['uniform', 'distance'],
        'model__KNN__p':[1, 2],
        'model__KNN__algorithm' : ['auto', 'ball_tree', 'kd_tree', 'brute'],

        'model__final_estimator__loss':['squared_error', 'absolute_error'],
        'model__final_estimator__learning_rate': [0.1, 0.01, 0.001, 0.0001, 0.00001],
        'model__final_estimator__n_estimators': [50, 100, 150, 200]
}

In [88]:
model = RandomizedSearchCV(estimator=pipe, param_distributions=param, cv=10, n_iter= 10, n_jobs=-1, verbose=2,)

In [92]:
model.fit(x_train, y_train)

Fitting 10 folds for each of 10 candidates, totalling 100 fits

RandomizedSearchCV(cv=10,
                   estimator=Pipeline(steps=[('Scaler', MinMaxScaler()),
                                             ('model',
                                              StackingRegressor(estimators=[('KNN',
                                                                             KNeighborsRegressor()),
                                                                            ('Random',
                                                                             RandomForestRegressor()),
                                                                            ('Net',
                                                                             ElasticNet())],
                                                                final_estimator=GradientBoostingRegressor()))]),
                   n_jobs=-1,
                   param_distributions={'model__KNN__algorithm': ['auto',
                                                                  'ball_tree',
                                                                  'kd_tree',
                                                                  'brute'],
                                        'mode...
                                                                     15, 20],
                                        'model__Random__min_samples_leaf': [1,
                                                                            2,
                                                                            4,
                                                                            6,
                                                                            8,
                                                                            10],
                                        'model__Random__min_samples_split': [2,
                                                                             4,
                                                                             6,
                                                                             10,
                                                                             15],
                                        'model__Random__n_estimators': [50, 100,
                                                                        150,
                                                                        200],
                                        'model__final_estimator__learning_rate': [0.1,
                                                                                  0.01,
                                                                                  0.001,
                                                                                  0.0001,
                                                                                  1e-05],
                                        'model__final_estimator__loss': ['squared_error',
                                                                         'absolute_error'],
                                        'model__final_estimator__n_estimators': [50,
                                                                                 100,
                                                                                 150,
                                                                                 200]},
                   verbose=2)

In [93]:
model.score(x_test, y_test)

0.6428248616698782

In [94]:
from sklearn.metrics import r2_score

In [96]:
y_pred = model.predict(x_test)

In [97]:
score = r2_score(y_test, y_pred)

In [98]:
score

0.6428248616698782